### PR TITLE
unix: Implement `uv_network_interfaces` on Solaris.

### PR DESCRIPTION
**Pull request by apaprocki**
The current implementation of `uv_interface_addresses` only works on
Solaris/X86_64 due to relying on `getifaddrs`, which is not provided
on Solaris/SPARC.

This patch implementes the new `uv_network_interfaces` function using
`getifaddrs` on Solaris/X86_64 and using the socket `ioctl` interface
on Solaris/SPARC to retrieve the same information.  Since this new
function provides a superset of the information provided by
`uv_interface_addresses`, the old function is implemented in terms of
the new one and will eventually be removed.

This is a platform needed to land #219.

### CODE REVIEW

**Comment by zenoamaro** [comment]
Thanks, that was ⭐️`F`⭐️`A`⭐️`S`⭐️`T`⭐️ !

Can you post a run of the tests from `test-platform-output.c`?

As in (feel free to mask physical addresses):

```
  name: en1
    is_up_and_running: 1
    is_loopback: 0
    is_point_to_point: 0
    is_promiscuous: 0
    has_broadcast: 1
    has_multicast: 1
    address: inet6 fe80::7256:81ff:fe92:92e5
    broadcast: none
    netmask: inet6 ffff:ffff:ffff:ffff::
    physical address: xx:xx:xx:xx:xx:xx
  name: en1
    is_up_and_running: 1
    is_loopback: 0
    is_point_to_point: 0
    is_promiscuous: 0
    has_broadcast: 1
    has_multicast: 1
    address: inet4 192.168.1.128
    broadcast: inet4 192.168.1.255
    netmask: inet4 255.255.255.0
    physical address: xx:xx:xx:xx:xx:xx
  name: en2
    is_up_and_running: 1
    is_loopback: 0
    ...
```

**Comment by apaprocki** [comment]
It looks like this (my interfaces don't have public physical addresses):

```
uv_interface_addresses:
  name: lo0
  internal: 1
  physical address: 00:00:00:00:00:00
  address: 127.0.0.1
  netmask: 255.0.0.0
  name: aggr1
  internal: 0
  physical address: 00:00:00:00:00:00
  address: 10.X.Y.Z
  netmask: 255.255.255.0
  name: aggr2
  internal: 0
  physical address: 00:00:00:00:00:00
  address: 10.X.Y.Z
  netmask: 255.255.255.0
  name: lo0
  internal: 1
  physical address: 00:00:00:00:00:00
  address: ::1
  netmask: ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff
uv_network_interfaces:
  name: lo0
    is_up_and_running: 1
    is_loopback: 1
    is_point_to_point: 0
    is_promiscuous: 0
    has_broadcast: 0
    has_multicast: 1
    address: inet4 127.0.0.1
    broadcast: none
    netmask: inet4 255.0.0.0
    physical address: none
  name: aggr1
    is_up_and_running: 1
    is_loopback: 0
    is_point_to_point: 0
    is_promiscuous: 0
    has_broadcast: 1
    has_multicast: 1
    address: inet4 10.X.Y.Z
    broadcast: inet4 10.X.Y.Z
    netmask: inet4 255.255.255.0
    physical address: none
  name: aggr2
    is_up_and_running: 1
    is_loopback: 0
    is_point_to_point: 0
    is_promiscuous: 0
    has_broadcast: 1
    has_multicast: 1
    address: inet4 10.X.Y.Z
    broadcast: inet4 10.X.Y.Z
    netmask: inet4 255.255.255.0
    physical address: none
  name: lo0
    is_up_and_running: 1
    is_loopback: 1
    is_point_to_point: 0
    is_promiscuous: 0
    has_broadcast: 0
    has_multicast: 1
    address: inet6 ::1
    broadcast: none
    netmask: inet6 ffff:ffff:ffff:ffff:ffff:ffff:ffff:ffff
    physical address: none
```

**Comment by zenoamaro** [comment]
Thanks! This will be useful when we'll retrofit the old interface. I'm merging this in.

**Comment by apaprocki** [comment]
I'll write the AIX support next and send you another PR.

**Pull request merged**
